# Generated by Django 4.1.5 on 2023-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapblottermodel',
            name='unit',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
