# Generated by Django 4.1.5 on 2023-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_contractm_major_mini_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapblottermodel',
            name='clearer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
