# Generated by Django 4.1.5 on 2023-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_swapblottermodel_clearer'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapblottermodel',
            name='bileteral_external',
            field=models.CharField(default='bilateral', max_length=100),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='buy_sell',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
