# Generated by Django 4.1.5 on 2023-03-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_swapblottermodel_bileteral_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brockeragem',
            name='derivatives',
            field=models.CharField(default='swaps', max_length=100),
            preserve_default=False,
        ),
    ]
