# Generated by Django 4.1.5 on 2023-03-27 07:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_brockeragem_derivatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureBlotterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.CharField(max_length=100)),
                ('trader_type', models.CharField(max_length=1000, null=True)),
                ('book', models.CharField(max_length=1000, null=True)),
                ('customer_company', models.CharField(max_length=10000, null=True)),
                ('customer_account', models.CharField(max_length=10000, null=True)),
                ('volume', models.CharField(max_length=1000, null=True)),
                ('contract', models.CharField(max_length=100, null=True)),
                ('Contract_Month', models.DateField(default=datetime.datetime.now, max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('approx_ep', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=1000, null=True)),
                ('broker', models.CharField(max_length=1000, null=True)),
                ('efs_code', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('unit', models.CharField(max_length=2000, null=True)),
                ('Clearer_rate', models.CharField(max_length=2000, null=True)),
                ('Exchange_rate', models.CharField(max_length=2000, null=True)),
                ('brockerage', models.CharField(max_length=2000, null=True)),
                ('total_fee', models.CharField(max_length=2000, null=True)),
                ('holiday', models.CharField(max_length=1000, null=True)),
                ('tick', models.CharField(max_length=2000, null=True)),
                ('bbl_mt_conversion', models.CharField(max_length=2000, null=True)),
                ('kbbl_mt_conversion', models.CharField(max_length=2000, null=True)),
                ('Trade_id', models.CharField(blank=True, max_length=250, null=True)),
                ('duplicate_id', models.CharField(default='none', max_length=100)),
                ('clearer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.clearerratem')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.strategy')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.traders')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FuturesBlottersModel',
        ),
    ]
