# Generated by Django 4.1.5 on 2023-03-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_futureblottermodel_clearer'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapblottermodel',
            name='First_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='LTD',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='MTM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='PNL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='Second_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='first_month_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='first_month_settle_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='futures_equiv_first',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='futures_equiv_first_kbbl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='futures_equiv_second',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='futures_equiv_second_kbbl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='fw_months',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='kbbl_mt_conversion',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='second_month_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='second_month_settle_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='total_PNL',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
