# Generated by Django 4.1.5 on 2023-03-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_swapblottermodel_first_month_swapblottermodel_ltd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureblottermodel',
            name='physical_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
