# Generated by Django 4.1.5 on 2023-03-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_futureblottermodel_physical_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureblottermodel',
            name='bileteral_external',
            field=models.CharField(default='bilateral', max_length=100),
        ),
    ]
