# Generated by Django 4.1.5 on 2023-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_futureblottermodel_bileteral_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapblottermodel',
            name='Trade_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
