# Generated by Django 4.1.5 on 2023-03-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_physicalblottermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhysicalBlotterModel',
        ),
    ]
