# Generated by Django 4.1.5 on 2023-03-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_physicalblottermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatetrademodel',
            name='Status',
            field=models.CharField(blank=True, default='New', max_length=100, null=True),
        ),
    ]
