# Generated by Django 4.1.5 on 2023-03-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_generatetrademodel_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TankCapacityM',
        ),
    ]
