# Generated by Django 4.1.5 on 2023-03-29 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_delete_tankcapacitym'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankCapacityM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_status', models.CharField(blank=True, default='Empty', max_length=100, null=True)),
                ('Density', models.FloatField(blank=True, null=True)),
                ('Nominal_capacity', models.FloatField()),
                ('Safe_fill_capacity', models.FloatField()),
                ('Prevailing_GOV', models.FloatField()),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('Qty_add_discharge', models.FloatField(blank=True, null=True)),
                ('Remaining_space', models.FloatField(blank=True, null=True)),
                ('current_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('Today', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('Remaining_days', models.IntegerField(blank=True, null=True)),
                ('Cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('Cost', models.FloatField(blank=True, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.portm')),
                ('Tank_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tanknumberm')),
                ('Tank_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tanktypem')),
                ('Terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.terminalm')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
