# Generated by Django 4.1.5 on 2023-04-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_generatetrademodel_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalblottermodel',
            name='Book',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
