# Generated by Django 4.1.5 on 2023-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_physicalblottermodel_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalblottermodel',
            name='Port',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
