# Generated by Django 4.1.5 on 2023-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_physicalblottermodel_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalblottermodel',
            name='Unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
