# Generated by Django 4.1.5 on 2023-04-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_physicalblottermodel_bl_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalblottermodel',
            options={'ordering': ['-Date']},
        ),
        migrations.AlterField(
            model_name='physicalblottermodel',
            name='Tank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
