# Generated by Django 4.1.5 on 2023-04-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_physicalblottermodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.CharField(max_length=100)),
                ('Trade_id', models.CharField(max_length=100)),
                ('Purchase_sales_ID', models.CharField(max_length=100)),
                ('Distribution_Type', models.CharField(max_length=100)),
                ('Delivery_mode', models.CharField(max_length=100)),
                ('Strategy', models.CharField(max_length=100)),
                ('Tank', models.CharField(max_length=100)),
                ('Vessal_name', models.CharField(max_length=120)),
                ('Port', models.CharField(max_length=100)),
                ('Terminal', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
                ('Shore_recieved', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(max_length=100)),
                ('Density', models.FloatField(blank=True, null=True)),
                ('dest_trade_strategy', models.CharField(max_length=100)),
                ('dest_container', models.CharField(blank=True, choices=[('Tank', 'Tank'), ('Vessal', 'Vessal')], max_length=100, null=True)),
                ('dest_port', models.CharField(max_length=100)),
                ('dest_terminal', models.CharField(max_length=100)),
                ('dest_vessal_op', models.CharField(blank=True, max_length=100, null=True)),
                ('dest_tank_num', models.CharField(blank=True, max_length=100, null=True)),
                ('dest_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_transfer_mode', models.CharField(blank=True, choices=[('None', 'None'), ('Truck', 'Truck')], max_length=100, null=True)),
                ('dest_unit', models.CharField(max_length=100)),
                ('dest_cargo_LD_QTY', models.FloatField()),
                ('source_cargo_LD_QTY', models.FloatField(blank=True, null=True)),
                ('dest_received_qty', models.FloatField()),
                ('dest_tank_end_qty', models.FloatField(blank=True, max_length=100, null=True)),
                ('dest_tank_remain_space', models.FloatField(blank=True, max_length=100, null=True)),
                ('dest_difference', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
