# Generated by Django 4.1.5 on 2023-04-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_inventorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='Tank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='Vessal_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
