# Generated by Django 4.1.5 on 2023-04-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_inventorymodel_tank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalblottermodel',
            name='Premium_discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
