# Generated by Django 4.1.5 on 2023-04-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_physicalblottermodel_premium_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapblottermodel',
            name='unpriced_volume',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
