# Generated by Django 4.1.5 on 2023-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_swapblottermodel_unpriced_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureblottermodel',
            name='approx_ep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
