# Generated by Django 4.1.5 on 2023-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_futureblottermodel_approx_ep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapblottermodel',
            name='approx_ep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
