# Generated by Django 4.1.5 on 2023-04-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_swapblottermodel_approx_ep'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapblottermodel',
            name='physical_code',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
