# Generated by Django 4.1.5 on 2023-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_swapblottermodel_physical_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureblottermodel',
            name='physica_blotter_connect',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='physica_blotter_connect',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
