# Generated by Django 4.1.5 on 2023-04-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_alter_contractm_block_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='book',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
