# Generated by Django 4.1.5 on 2023-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_inventorymodel_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymodel',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
