# Generated by Django 4.1.5 on 2023-04-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_inventorymodel_m3_physicalblottermodel_m3'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
