# Generated by Django 4.1.5 on 2023-04-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_inventorymodel_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatetrademodel',
            name='deal_current_qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
