# Generated by Django 4.1.5 on 2023-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_generatetrademodel_deal_current_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalblottermodel',
            name='current_qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
