# Generated by Django 4.1.5 on 2023-05-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_physicalblottermodel_current_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='duplicate_id',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
