# Generated by Django 4.1.5 on 2023-05-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_inventorymodel_duplicate_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brockeragem',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='clearerratem',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='companyinvestmentmodel',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='contractm',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='futureblottermodel',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='futureltd',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='swapblottermodel',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='brockeragem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='brockeragem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='clearerratem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clearerratem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinvestmentmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinvestmentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contractm',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contractm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='futureblottermodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='futureblottermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='futureltd',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='futureltd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblottermodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblottermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='swapblottermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
