# Generated by Django 4.1.5 on 2023-05-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_swapblottermodel_total_n_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureblottermodel',
            name='Contract_Month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
