# Generated by Django 4.1.5 on 2023-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_alter_futureblottermodel_contract_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapblottermodel',
            name='bileteral_external',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
