# Generated by Django 4.1.5 on 2023-05-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_alter_swapblottermodel_bileteral_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapblottermodel',
            name='bileteral_external',
            field=models.CharField(default='bilateral', max_length=100),
        ),
    ]
